---
ec2_instances:
  - name: Ubuntu-server
    image_id: ami-xxxxxxx
    instance_type: t3.micro

  - name: AmazonLinux-server
    image_id: ami-xxxxxxxx
    instance_type: t3.micro

  - name: RHEL-server
    image_id: ami-xxxxxxxxx
    instance_type: t3.micro

aws_region: ap-southeast-2

key_name: ansible
security_group: sg-xxxxxxxxxxxxxx
subnet_id: subnet-xxxxxxxxxxxx
