---
- name: Create EC2 instances
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Launch EC2 instances
      amazon.aws.ec2_instance:
        name: "{{ item.name }}"
        image_id: "{{ item.image_id }}"
        instance_type: "{{ item.instance_type }}"

        region: "{{ aws_region }}"
        key_name: "{{ key_name }}"
        security_group: "{{ security_group }}"
        subnet_id: "{{ subnet_id }}"

        wait: true
        tags:
          Environment: Test
          ManagedBy: Ansible
          OS: "{{ item.name }}"

      loop: "{{ ec2_instances }}"
      register: ec2_output

    - name: Display instance Details
      debug:
        msg:
          - "Instance Name is {{ item.item.name }}"
          - "Public IP: {{ item.instances[0].public_ip_address }}"
      loop: "{{ ec2_output.results }}"
